apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-webapp-sample-with-dockerfile-zrei
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-webapp-sample-with-dockerfile-zrei
    app.kubernetes.io/part-of: gwsd
  name: go-webapp-sample-with-docoo4j
  namespace: pmacik-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-webapp-sample-with-dockerfile-zrei
    weight: 100
status: {}
