apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-webapp-sample-with-dockerfile-zrei
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-webapp-sample-with-dockerfile-zrei
    app.kubernetes.io/part-of: gwsd
  name: go-webapp-sample-with-dockerfile-zrei
  namespace: pmacik-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: go-webapp-sample-with-dockerfile-zrei
status:
  loadBalancer: {}
